packages:
  - apps/hy-bff-fastify
  - apps/hy-component-preview
  - apps/hy-storybook
  - apps/hy-taxes
  - packages/hy-ai-tools
  - packages/hy-component-template
  - packages/hy-design-system
  - packages/hy-eslint-config
  - packages/hy-jest-config
  - packages/hy-prettify-config
  - packages/hy-tokens
  - packages/hy-theme-provider
  - packages/hy-tsdown-config
  - packages/hy-typescript-config
  - packages/hy-config
  - packages/hy-design-mcp
  - packages/hy-ai-rum

onlyBuiltDependencies:
  - esbuild
  - unrs-resolver
  - better-sqlite3
  - koffi
